Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ce21b51cb31a48b8 # Amazon Linux AMI in Oregon
      SubnetId: subnet-05c2ca11c857bf90c
