AWSTemplateFormatVersion: 2010-09-09
Description: Creates public/private instances and SGs within a pre-built VPC.

# ----------------- TO DO ----------------------

# [x] 2 EC2 instances- public jumpbox, and private webserver. 
# [ ] use cfn-init on the private instance
# [ ] IAM role for EC2
# [ ] EC2 instance profile for private instance

# stretch goal: parameters file which you can use to pass the subnet ids for the EC2 instances


Resources:
# ----------------- INSTANCES ----------------------
  PublicInstance: 
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ce21b51cb31a48b8
      KeyName: MyUSWest2KP
      SubnetId: subnet-06fd64678dff8d3b8 # public subnet
      Tags: 
        - Key: Name
          Value: week4-public-instance
      SecurityGroupIds:
        - !Ref SecurityGroupPublic

  PrivateInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ce21b51cb31a48b8 
      KeyName: MyUSWest2KP
      SubnetId: subnet-086d2f36145eda3d3 # private subnet.
      Tags:
        - Key: Name
          Value: week4-private-instance
      SecurityGroupIds:
        - !Ref SecurityGroupPrivate 

# ----------------- PUBLIC Security Group CREATION and RULES ----------------------
  SecurityGroupPublic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: public-security-group
      GroupDescription: An SG that holds a public instance.
      VpcId: vpc-01514eb507db3e20a
      Tags: 
        - Key: Name
          Value: sg-public

  SecurityGroupPublicIngressRuleSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupPublic
      IpProtocol: tcp 
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

# ----------------- PRIVATE Security Group CREATION and RULES ----------------------
  SecurityGroupPrivate:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: private-security-group
      GroupDescription: An SG that holds a private instance.
      VpcId: vpc-01514eb507db3e20a
      Tags: 
        - Key: Name
          Value: sg-private
      
  SecurityGroupPrivateIngressRuleSSH:
    Type: AWS::EC2::SecurityGroupIngress 
    Properties:
      GroupId: !Ref SecurityGroupPrivate
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !GetAtt SecurityGroupPublic.GroupId

# ----------------- cfn-init ----------------------
# Resources:
#   VirtualMachine:
#     Type: 'AWS::EC2::Instance'
#     Metadata:
#       'AWS::CloudFormation::Init':
#         config:
#          #file
#     Properties:
#       #[...]
#       UserData: 
#         'Fn::Base64': !Sub | 
#         /opt/aws/bin/cfn-init -v --resource VirtualMachine --region us-west-2 --stack ${nameofstack}



# ----------------- STRETCH GOAL ---- S3 Bucket creation ----------------------
# Resources: # Always either making an obj or list item. 
#   MyS3Bucket: # creating a bucket with CloudFormation
#     Type: AWS::S3::Bucket 
#     Properties:
#       BucketName: julie-bucket-cloud-f
#       AccessControl: PublicRead
#       WebsiteConfiguration:
#         IndexDocument: index.html